# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Luxtronik Plugin für SmartHomeNG v1.7.2 und höher'
        en: 'Lustronic plugin for SmartHomeNG v1.7.2 and up'
    maintainer: Michael Schatz
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.7              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: False           # plugin supports multi instance
    restartable: True
    classname: luxtronik         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    host:
        type: str
        description:
            de: 'IP-Adresse der Luxtronik Steuerung'
            en: 'IP address of the Luxtronik controller'

    port:
        type: int
        default: '8889'
        description:
            de: 'IP Port der Luxtronik Steuerung'
            en: 'IP Port of the Luxtronik controller'

    cycle:
        type: int
        # If 'mandatory' is specified, a 'default' attribute must not be specified
        default: 60
        mandatory: True
        description:
            de: 'Zykluszeit (in Sekunden)'
            en: 'Cycle time (in seconds)'

item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    luxtronik_parameters:
        type: str
        description:
            de: 'Gibt einen Parameterwert an (3003)'
            en: 'Specifies a parameter value (3003)'
    luxtronik_calculations:
        type: str
        description:
            de: 'Gibt einen Messwert an (3004)'
            en: 'Specifies a measurment value (3004)'
    # Funktion noch unbekannt!        
    #luxtronik_visibilities:
    #    type: str
    #    description:
    #        de: 'Gibt einen Messwert an (3005)'
    #        en: 'Specifies a measurment value (3005)'

item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
